### ISSUE TITLE
Why node user ?

### ISSUE THREAD

**Issue by EmrysMyrddin** [aldrio/adorable-avatars#1]
Why did you set the user to `node` ? It prevent the API to run on port 80 and to be able to be directly exposed as web app.

Do you think you can change this ?

**Comment by aldrio** [comment]
It's best to run containers as unprivileged users whenever possible. Remapping the port to 80 (`-p 80:8080`) still works, is that an option?

**Comment by EmrysMyrddin** [comment]
Yes, I managed to make it works, just wondered why this choice :-)

Why is it best ? Containers are isolated right ? Running as root should not make much difference ?

**Comment by aldrio** [comment]
It's another layer of security in case a container gets compromised, which I have no idea how this one would lol, but still. If a service got compromised then running as a non root user limits the possibilities of an attacker. This explains it better than I can if you're still curious: https://americanexpress.io/do-not-run-dockerized-applications-as-root/
